insalan_news:
    resource: "@InsaLanNewsBundle/Controller/"
    type:     annotation
    prefix:   /

insalan_stream:
    resource: "@InsaLanStreamBundle/Controller/"
    type:     annotation
    prefix:   /streams

insalan_tournament:
    resource: "@InsaLanTournamentBundle/Controller/"
    type:     annotation
    prefix:   /tournament

#insalan_pizza:
    #resource: "@InsaLanPizzaBundle/Controller/"
    #type:     annotation
    #prefix:   /pizza

insalan_information:
    resource: "@InsaLanInformationBundle/Controller/"
    type:     annotation
    prefix:   /infos

insalan_user:
    resource: "@InsaLanUserBundle/Controller/"
    type:     annotation
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

#sonata_user:
#    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
#    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
