services:
    sonata.admin.news.news:
        class: InsaLan\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Actualités", label: "News" }
        arguments:
            - ~
            - InsaLan\NewsBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanNewsBundle]]

    sonata.admin.news.slider:
        class: InsaLan\NewsBundle\Admin\SliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Actualités", label: "Slider" }
        arguments:
            - ~
            - InsaLan\NewsBundle\Entity\Slider
            - ~
        calls:
            - [ setTranslationDomain, [InsaLanNewsBundle]]
